/** Keyword abilities as the Apprentice explains them. Sorted at render time. */
export const KEYWORDS: Array<{ name: string; text: string }> = [
  { name: 'Deathtouch', text: 'Any amount of damage this deals to a creature is enough to destroy it.' },
  { name: 'Defender', text: 'Cannot attack.' },
  { name: 'Double strike', text: 'Deals combat damage in both the first-strike step and the regular step.' },
  { name: 'Enchant', text: 'An Aura with "enchant creature" attaches to a creature as it enters; if that creature leaves, the Aura goes to the graveyard.' },
  { name: 'Equip {N}', text: 'Pay {N} at sorcery speed to attach this Equipment to a creature you control. It stays when the creature dies.' },
  { name: 'First strike', text: 'Deals combat damage before creatures without first strike.' },
  { name: 'Flash', text: 'May be cast any time you could cast an instant.' },
  { name: 'Flying', text: 'Can be blocked only by creatures with flying or reach.' },
  { name: 'Haste', text: 'Can attack and use tap abilities the turn it arrives.' },
  { name: 'Hexproof', text: 'Cannot be the target of spells or abilities your opponents control.' },
  { name: 'Indestructible', text: 'Cannot be destroyed by damage or by "destroy" effects. It can still be exiled, sacrificed or given -X/-X.' },
  { name: 'Infect', text: 'Deals damage to creatures as -1/-1 counters and to players as poison counters.' },
  { name: 'Lifelink', text: 'Damage this deals also gains its controller that much life.' },
  { name: 'Menace', text: 'Cannot be blocked except by two or more creatures.' },
  { name: 'Proliferate', text: 'Choose any number of permanents and players with counters; give each one more counter of a kind it already has.' },
  { name: 'Protection from X', text: 'Cannot be damaged, enchanted, equipped, blocked or targeted by anything with quality X.' },
  { name: 'Reach', text: 'Can block creatures with flying.' },
  { name: 'Scry N', text: 'Look at the top N cards of your library; put any number on the bottom and the rest back on top in any order.' },
  { name: 'Surveil N', text: 'Like scry, but the cards you do not keep go to the graveyard.' },
  { name: 'Toxic N', text: 'A player dealt combat damage by this also gets N poison counters.' },
  { name: 'Trample', text: 'Damage beyond what is needed to destroy its blockers is dealt to the player or planeswalker it attacks.' },
  { name: 'Vigilance', text: 'Attacking does not cause it to tap.' },
  { name: 'Ward {N}', text: 'A spell or ability an opponent controls that targets it is countered unless that player pays {N}.' },
  { name: 'Cascade', text: 'When cast, exile cards from the top of your library until you hit a nonland card that costs less; you may cast it free.' },
  { name: 'Convoke', text: 'Tap untapped creatures you control to help pay for this spell, one mana each.' },
  { name: 'Cycling {N}', text: 'Pay {N} and discard this card to draw a card.' },
  { name: 'Flashback {N}', text: 'May be cast from your graveyard for {N}; it is exiled afterwards.' },
  { name: 'Kicker {N}', text: 'May pay {N} extra as you cast it for an added effect.' },
  { name: 'Eminence', text: 'The ability works while the commander is in the command zone as well as on the battlefield.' },
  { name: 'Partner', text: 'Two legendary creatures with partner may both be your commanders; the deck uses both colour identities.' },
];
